lsi: false
safe: true
source: /HackingStuff
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

remote_theme: alshedivat/al-folio
